#image: gitlab/dind

variables:
  VERSION: "1.0.1"
  SERVICE_NAME: "DongBoHoSo"
  PATH_JAR: "E:/setup/HaiDuong/DongBoHS/DongBoHS-0.0.1-SNAPSHOT.jar"
  
  SERVICE_NAME_PROD: "DongBoHoSo"
  PATH_JAR_PROD: "C:/Setup/DongBoHoSo/DongBoHS-0.0.1-SNAPSHOT.jar"
  GIT_STRATEGY: clone #cấu hình git clone mặc định 
  TOKEN: HxLsDaGewu5yhxK_7cjf
  URL_REP: gitlab.digital-id.vn/duongbach48/dmhosohd.git
  
stages:
  - build
  - merge_master
  - buildProd

# Build fo
BuildAPP API job:
  stage: build
  tags:
    - deploy_dev
  script:
    - git pull origin dev
    - mvn clean package -Pdev -DskipTests
    - cd target
    - Copy-Item -Path *.jar -Destination $PATH_JAR
    - cd..
    - .\ci_settup.ps1
    - net START $SERVICE_NAME
    - mvn clean
    - exit
  only:
    - dev

merge master:
  environment:
    name: dev
  stage: merge_master
  tags:
    - deploy_dev
  script:
    - git config --global user.name "duongbach48"
    - git config --global user.email "duongbach48@gmail.com"
    - mvn clean package -Pprod -DskipTests
    - Remove-Item 'src' -Recurse
    - git checkout -b prod
    - git rm src -r
    - git rm .gitlab-ci.yml -r 
    - git rm pom.xml -r
    - git commit -m"commit"
    - git pull https://gitlab-ci-token:$TOKEN@$URL_REP prod
    - New-Item -ItemType Directory -Force -Path deploy_product
    - Copy-Item -Path target\*.jar -Destination deploy_product
    - git add --all
    - git commit -m'deploy prod'
    - git push https://gitlab-ci-token:$TOKEN@$URL_REP HEAD:prod
  when: manual
  only:
    - dev

BuildAPP API job prod:
  stage: buildProd
  tags:
    - deploy_prod
  script:
    - git config --global user.name "duongbach48"
    - git config --global user.email "duongbach48@gmail.com"
    - git checkout -b prod
    - git pull https://gitlab-ci-token:$TOKEN@$URL_REP prod
    - cd deploy_product
    - Get-ChildItem -File -Recurse | foreach { $_.Delete()}
    - Copy-Item -Path *.jar -Destination $PATH_JAR_PROD
    - cd..
    - .\ci_settup_prod.ps1
    - net START $SERVICE_NAME_PROD
    - exit
  needs:
    - merge master
  only:
    - dev