#image: gitlab/dind

variables:
  VERSION: "1.0.1"
  SERVICE_NAME: "Dong_bo_ho_so"
  PATH_JAR: "E:/LGSP_HAIDUONG/DongBoHS/DongBoHS-0.0.1-SNAPSHOT.jar"

# services:
#   - docker:dind

before_script:
  - git --version

stages:
  - setup
  - test
  - build
  - clear
  - deployment

# Pull code ve1
Setup EnviromentDesktop job:
  stage: setup
  tags:
    - deploy_localhost
  script:
    - git pull origin TrangBtt
    - exit
  only:
    - TrangBtt

test:
  stage: test
  tags:
    - deploy_localhost
  script:
    - cd
    - mvn -version
    - exit
  only:
    - TrangBtt

# Build fo
BuildAPP API job:
  stage: build
  tags:
    - deploy_localhost
  script:
    - mvn clean package
    - cd target
    - $arrService = Get-Service -Name $SERVICE_NAME; if ($arrService.Status -ne 'Stopped'){ net STOP $SERVICE_NAME } else { echo 'service is stop' }
    # backup cmd
    #- ren D:\setup\CI_CD\TEST\email_cong_vu.jar email_cong_vu-%date:~10,4%%date:~7,2%%date:~4,2%_%time:~0,2%%time:~3,2%.jar
    # backup PowerShell
    - ren $PATH_JAR email_cong_vu-$(get-date -f yyyyMMdd_HHmm).jar
    - Copy-Item -Path *.jar -Destination $PATH_JAR
    - exit
  only:
    - TrangBtt

# Clear fo
ClearAPP API job:
  stage: clear
  tags:
    - deploy_localhost
  script:
    - exit
  only:
    - TrangBtt

# Run API
Deploy API job:
  stage: deployment
  tags:
    - deploy_localhost
  script:
    - net START $SERVICE_NAME
    - exit
  when: always
  only:
    - TrangBtt

